# modified from: https://github.com/f1tenth/f1tenth_gym_ros/blob/main/config/sim.yaml

bridge:
  ros__parameters: 
    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # ego starting pose on map
    sx: 0.0
    sy: 0.0
    stheta: 0.0

    # teleop
    using_teleop: True
